version: '3.7'

networks:
  keycloak-tier:

volumes:
  keycloak-config-data:
  keycloak-db-data:

services:
  keycloak-db:
    image: "postgres:12.0-alpine"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pgpwd
      POSTGRES_DB: "keycloak-db"
    networks:
      - keycloak-tier
    ports:
      - 5432:5432
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:8.0.0
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    volumes:
      - keycloak-config-data:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=kcadmin
      - KEYCLOAK_HTTP_PORT=8080
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=pgpwd
      - DB_ADDR=keycloak-db
      - DB_PORT=5432
      - DB_DATABASE=keycloak-db
    networks:
      - keycloak-tier
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
